# Tema 2

Topics:
1. Metoda substitutiei inverse
2. Algoritmul de Elminiare Gauss

In [487]:
import numpy as np
import unittest
import random

np.random.seed(10)

# functions that need to be implemented
from tema2 import substitution_method#, get_inv, gauss_algorithm

# dummy functions that mirror standard methods from libraries (but you'll have to discover them)
# from tema2 import get_norm, lib_solve, lib_inv

# from tema2 import plot_matrix_evolution

np.set_printoptions(suppress=True)

## 1. Metoda substitutiei inverse

**TL;DR:** Metoda substituiei inverse rezolva sisteme linare in care matricea asociata sistemului este triunghiulara (inferior sau superior).

* **Ce este o matrice triunghiulara superior?** O matrice triunghiulara superior este o matrice care are valori nule sub diagonala principala. 

In [488]:
# generate a 4x4 matrix with elements from 1 to 16
A = (np.arange(4*4) + 1).reshape(4, 4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [489]:
# generated superior triangular matrix from A
np.triu(A)

array([[ 1,  2,  3,  4],
       [ 0,  6,  7,  8],
       [ 0,  0, 11, 12],
       [ 0,  0,  0, 16]])

* **Ce este o matrice triunghiulara inferior?** O matrice triunghiulara inferior este o matrice care are valori nule deasupra diagonala principala. 

In [490]:
# generated inferior triangular matrix from A
np.tril(A)

array([[ 1,  0,  0,  0],
       [ 5,  6,  0,  0],
       [ 9, 10, 11,  0],
       [13, 14, 15, 16]])

### Metoda substitutiei inverse
Fie sistemul liniar:
$$
A x=b
$$

unde matricea sistemului $A$ este **triunghiulară superior**. Pentru a găsi soluţia unică a sistemului, trebuie ca matricea să fie nesingulară. Determinantul matricelor triunghiulare este dat de formula:
$$
\operatorname{det} A=a_{11} a_{22} \cdots a_{n n}
$$
Prin urmare, pentru rezolvarea sistemului vom presupune că:
$$
\operatorname{det} A \neq 0 \Longleftrightarrow a_{i i} \neq 0 \quad \forall i=1,2, \ldots, n
$$
Vom considera sistemul liniar cu matrice superior triunghiulară:

\begin{align*}
a_{11} x_{1}+\cdots+a_{1 i} x_{i}+\cdots+a_{1 n-1} x_{n-1}+a_{1 n} x_{n}&=b_{1}\\
\cdots\\
a_{i i} x_{i}+\cdots+a_{i n-1} x_{n-1}+a_{i n} x_{n}&=b_{i}\\
\cdots\\
a_{n-1 n-1} x_{n-1}+a_{n-1 n} x_{n}&=b_{n-1}\\
a_{n n} x_{n}&=b_{n}\\
\end{align*}

Necunoscutele $x_{1}, x_{2}, \ldots, x_{n}$ se deduc pe rând, folosind ecuaţiile sistemului de la ultima către prima. Din ultima ecuaţie, deducem valoarea lui $x_{n}$ :
$$
x_{n}=\frac{b_{n}}{a_{n n}}
$$
Folosind valoarea lui $x_{n}$ calculată mai sus, din penultima ecuaţie obţinem:
$$
x_{n-1}=\frac{b_{n-1}-a_{n-1 n} x_{n}}{a_{n-1 n-1}}
$$


Continuăm să calculăm valori $x_{i}$ din ecuaţiile sistemului:
$$
x_{i}=\frac{b_{i}-a_{i i+1} x_{i+1}-\cdots-a_{i n} x_{n}}{a_{i i}}
$$
Din prima ecuaţie găsim valoarea lui $x_{1}$ :
$$
x_{1}=\frac{b_{1}-a_{12} x_{2}-\cdots-a_{1 n} x_{n}}{a_{11}}
$$
Procedeul descris mai sus poartă numele de metoda substituţiei inverse pentru rezolvarea sistemelor liniare cu matrice superior triunghiulară:
$$
x_{i}=\frac{\left(b_{i}-\sum_{j=i+1}^{n} a_{i j} x_{j}\right)}{a_{i i}} \quad, \quad i=n, n-1, \ldots, 2,1
$$

#### Exemplu pentru metoda substitutiei inverse
$$
\left(\begin{array}{ccc}
3 & 1 & -5 \\
& -2 & 4 \\
& & 2
\end{array}\right)\left(\begin{array}{l}
x_{1} \\
x_{2} \\
x_{3}
\end{array}\right)=\left(\begin{array}{c}
1 \\
10 \\
6
\end{array}\right)$$

#### Rezolvare:

$$x_n = \frac{b_n}{a_{nn}} \Rightarrow x_3 = \frac{b_3}{a_{33}} = \frac{6}{2} = 3$$


$$
x_{i}=\frac{\left(b_{i}-\sum_{j=i+1}^{n} a_{i j} x_{j}\right)}{a_{i i}} \quad, \quad i=n, n-1, \ldots, 2,1
\Rightarrow
x_2=\frac{10 - (4 * 3)}{-2}=1
$$

$$
x_1=\frac{1 - ((1 * 1) + (-5 * 3))}{3} = \frac{1 - (-14)}{3} = \frac{15}{3} = 5
$$

In [491]:
def substitution_method(A, b, n):
    if A[0][0] == 0:
        raise ValueError("The matrix is singular")
    else:
        x = list(0 for j in range(0, n))
        x[n - 1] = b[n - 1] / A[n - 1][n - 1]
        for i in range(n - 2, -1, -1):
            suma = 0
            for j in range(i + 1, n):
                suma = suma + A[i][j] * x[j]
            v = b[i] - suma
            x[i] = v / A[i][i]

        return x

In [492]:
# Generate random superior triangular system
n = 10
A = np.random.randint(low=1, high=100, size=n*n).reshape(n, n)
A = np.triu(A)
b = np.random.randint(low=1, high=100, size=n)

A, b

(array([[10, 16, 65, 29, 90, 94, 30,  9, 74,  1],
        [ 0, 37, 17, 12, 55, 89, 63, 34, 73, 79],
        [ 0,  0, 55, 78, 70, 14, 26, 14, 93, 87],
        [ 0,  0,  0, 13, 66, 32, 58, 37, 28, 19],
        [ 0,  0,  0,  0, 95, 12, 29, 75, 89, 10],
        [ 0,  0,  0,  0,  0, 12, 18, 47,  8, 76],
        [ 0,  0,  0,  0,  0,  0,  6,  5, 72, 89],
        [ 0,  0,  0,  0,  0,  0,  0, 16,  7, 86],
        [ 0,  0,  0,  0,  0,  0,  0,  0, 43, 58],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 24]]),
 array([ 4, 30, 17, 85, 83, 15, 52, 80, 18, 51]))

In [493]:
# Apply substitution method
x = substitution_method(A, b, n)
x

[-138.82179681562053,
 -12.535229963049725,
 40.2585788731872,
 -33.34281160750714,
 4.585178243574051,
 -6.084060077519383,
 10.977107558139537,
 -5.351017441860465,
 -2.447674418604651,
 2.125]

In [494]:
# Compute norm between the matrix multiplication of A and our solution
diff = A @ x - b
diff

array([ 0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.])

In [495]:
# Test if the matrix is singular
A[2, 2] = 0

try: 
    x = substitution_method(A, b, n)
except Exception as e: 
    print(e)

C:\Users\cosmi\AppData\Local\Temp\ipykernel_18724\614015635.py:12: RuntimeWarning:

divide by zero encountered in double_scalars

C:\Users\cosmi\AppData\Local\Temp\ipykernel_18724\614015635.py:10: RuntimeWarning:

invalid value encountered in double_scalars



### 2. Algoritmul de eliminare Gauss


Ideea de rezolvare este de a transforma succesiv sistemul folosind operaţii elementare (ce nu modifică soluţia sistemului) şi a aduce matricea $A$ la o formă superior triunghiulară . Algoritmul se desfăşoară în $(n-1)$ paşi. La un pas $l$ oarecare se transformă coloana $l$ a matricei $A$ în formă superior triunghiulară fără a modifica forma triunghiulară a primelor $(l-1)$ coloane.


**Pas $l$ :** Presupunem că elementul de pe poziţia $(l, l)$ numit şi element pivot este nenul, $a_{l l} \neq 0$. Pentru $i=l+1, \ldots, n$ se înmulteste linia $l$ a matricei $A$ $\mathrm{cu}\left(-a_{i l} / a_{l l}\right)$ şi se adună la linia $i$. Schimbare se face şi asupra componentei $i$ a vectorului $b$. Matricea $A$ şi vectorul $b$ se modifică astfel:
$$
\begin{aligned}
&a_{i j}^{\prime}=a_{i j}-\frac{a_{i l}}{a_{l l}} a_{l j} \quad, \quad i=\overline{l+1, n}, j=\overline{l+1, n}  &(5)\\
&b_{i}^{\prime}=b_{i}-\frac{a_{i l}}{a_{l l}} b_{l} \quad, \quad i=\overline{l+1, n}  &(6)\\
&a_{i l}^{\prime}=0 \quad, \quad i=\overline{l+1, n}, &(7)\\
&a_{i j}^{\prime}=a_{i j} \quad, \quad b_{i}^{\prime}=b_{i} \text { pentru restul indicilor } i, j
\end{aligned}
$$

In formula $(5)$ factorul $f=\frac{a_{i l}}{a_{l l}}$ se calculează în afara buclei for pentru $j$.

#### Alegerea pivotului $a_{l l} \neq 0\left(\left|a_{l l}\right|>\epsilon\right)$

Pentru a aduce pe poziţia $(l, l)$ un element nenul avem trei posibilităti:
1. **Varianta fără pivotare** : Se alege primul indice $i_{0} \in\{l, l+1, \cdots, n\}$ astfel ca $a_{i_{0} l} \neq 0$. Se interschimbă liniile $i_{0}$ şi $l$ ale matricei $A$ şi componentele $i_{0}$ şi $l$ ale vectorului $b$.
2. **Varianta cu pivotare parțială**: 
Se alege indicele $i_{0} \in\{l, l+1, \cdots, n\}$ astfel ca:
$$
\left|a_{i_{0} l}\right|=\max \left\{\left|a_{i l}\right|, i=\overline{l, n}\right\} .
$$
Se interschimbă liniile $i_{0}$ şi $l$ ale matricei $A$ şi componentele $i_{0}$ şi $l$ ale vectorului $b$.
3. **Varianta cu pivotare totală** 
Se aleg indicii $i_{0}, j_{0} \in\{l, l+1, \cdots, n\}$ astfel ca:
$$
\left|a_{i_{0} j_{0}}\right|=\max \left\{\left|a_{i j}\right|, i=\overline{l, n}, j=\overline{l, n}\right\} .
$$
Se interschimbă liniile $i_{0}$ şi $l$, coloanele $j_{0}$ şi $l$ ale matricei $A$ şi componentele $i_{0}$ şi $l$ ale vectorului $b$.
Dacă după efectuarea pivotării (indiferent de varianta de pivotare aleasă) elementul pivot este nul
$$
a_{l l}=0 \quad \sim \quad \operatorname{abs}(a[l, l]) \leq \epsilon
$$
atunci matricea $A$ este singulară.

**Observaţii:**
1. In pasul Gauss $l$ $(5)+(6)+(7)$ calculele se pot efectua în matricea $A$ iniţială $\left(a^{\prime}=a\right)$.

2. Dacă pentru memorarea matricei $A$ şi a vectorului $b$ se foloseşte o matrice cu $n$ linii şi $(n+1)$ coloane, vectorul $b$ fiind memorat în coloana $(n+1)$ a matricei $A$, calculele $(6)$ sunt incluse în $(5)$ pentru $j=n+1$; se simplifică şi interschimbarea liniilor $i_{0}$ şi $l$.

3. Dacă pivotul se alege folosind varianta a 3-a, cu pivotare totală, la final trebuie să avem grijă sa restabilim ordinea iniţială a componentelor vectorului soluţie (ţinând cont de coloana $j_{0}$ a pivotului de la fiecare pas).

#### Exemplu pentru algoritmul de eliminare Gauss

Youtube: https://www.youtube.com/watch?v=2j5Ic2V7wq4 - puteti cauta si altele pt "Gaussian elimination"

Exemplul din tema (fara pivotare):
$$
A=\left(\begin{array}{lll}
2 & 0 & 1 \\
0 & 2 & 1 \\
4 & 4 & 6
\end{array}\right) x=\left(\begin{array}{c}
5 \\
1 \\
14
\end{array}\right)
$$

1. **Pasul 1:** Verificam daca $a_{11}$ este nenul. Raspunsul este da, deci $a_{11}$ este un pivot valid. Astfel putem incepe sa facem valorile $a_{21}$ si $a_{31}$ nule.
  * $a_{21}$ este deja nul, deci vom alsa linia $2$ neschimbata
  * $a_{31}$ nu este nul, deci incercam sa facem elementul 0 inmultind linia 3 cu valoarea $(−𝑎_{𝑖𝑙}/𝑎{𝑙𝑙})$ unde $i = 3$, asadar Linia 3 devine $Linia3-2 * Linia 1$
  Asadar
  $$
A=\left(\begin{array}{lll}
2 & 0 & 1 \\
0 & 2 & 1 \\
0 & 4 & 4
\end{array}\right) x=\left(\begin{array}{c}
5 \\
1 \\
4
\end{array}\right)
$$

1. **Pasul 2:** Verificam daca $a_{22}$ este nenul. Raspunsul este da, deci $a_{22}$ este un pivot valid. Astfel putem incepe sa facem valorea $a_{23}$ nula.
  * $a_{23}$ nu este nula, deci incercam sa facem elementul 0 inmultind linia 2 cu -4/2 si adunand la linia 3
  Asadar
  $$
A=\left(\begin{array}{lll}
2 & 0 & 1 \\
0 & 2 & 1 \\
0 & 0 & 2
\end{array}\right) x=\left(\begin{array}{c}
5 \\
1 \\
2
\end{array}\right)
$$

In [496]:
def search_pivot(matrix, column,n):
    max = 0
    index = 0
    for i in range(column, n):
        if max < abs(matrix[i][column]):
            max = abs(matrix[i][column])
            index = i
    return index


def interschimba_linii(A, b, l, index):
    A[[l, index]] = A[[index, l]]
    aux = b[index]
    b[index] = b[l]
    b[l]=aux
    return A, b

In [497]:
def gauss_algorithm(A, b, n):
    l = 0
    evo=list()
    evo.append(np.c_[A, b])
    index = search_pivot(A, l, n)
    A, b = interschimba_linii(A, b, l, index)
    b_prim = b
    a_prim = A
    while l < n - 1 and a_prim[l][l] != 0:
        for i in range(l + 1, n):
            f = a_prim[i][l] / a_prim[l][l]
            for j in range(l + 1, n):
                a_prim[i][j] = a_prim[i][j] - f * a_prim[l][j]
            b_prim[i] = b_prim[i] - f * b_prim[l]
            a_prim[i][l] = 0
        l += 1
        index = search_pivot(a_prim, l, n)
        a_prim, b_prim = interschimba_linii(a_prim, b_prim, l, index)
        evo.append(np.c_[A, b])

    if A[l][l] == 0:
        print("Matrice singulara")
    else:
        x = substitution_method(a_prim, b_prim, n)
        diff = a_prim @ x - b_prim
        for o in diff:
            if int(o) != 0:
                print("Solutie gresita")
            else:
                return a_prim, b_prim,evo

In [498]:
# Generate random superior triangular system
n = 10
A = np.random.randint(low=1, high=100, size=n*n).reshape(n, n)
b = np.random.randint(low=1, high=100, size=n)
A, b

(array([[54, 26, 49, 18, 33, 82, 81, 42, 91, 13],
        [31, 82, 18, 17,  1, 32, 74, 65, 39, 23],
        [97, 67, 68, 63, 96, 28, 83, 63, 78, 49],
        [94, 76, 87, 38, 12, 22, 34, 96, 44, 89],
        [97, 74, 41, 44, 91, 72,  9, 86, 73, 29],
        [31, 90, 26, 79, 82, 86, 63, 14, 42, 34],
        [ 5, 88, 95, 29, 40, 92, 10,  8, 23, 33],
        [ 4, 10, 53, 77, 69, 31, 71, 75, 31, 10],
        [ 3, 66, 14, 76, 53,  6, 94, 85, 49, 63],
        [43, 35, 41, 47, 33, 95, 87, 59, 70, 46]]),
 array([19, 51, 45,  2, 64, 78, 19, 28, 84, 38]))

In [499]:
A_gauss, b_gauss, evo = gauss_algorithm(A, b, n=n) # here is presented the first method
A_gauss, b_gauss

(array([[ 97,  67,  68,  63,  96,  28,  83,  63,  78,  49],
        [  0,  84,  91,  25,  35,  90,   5,   4,  18,  30],
        [  0,   0, -69,  37,  22,   4,  31,  -9,   2,  -6],
        [  0,   0,   0,  93,  75,  23,  84,  65,  26,   0],
        [  0,   0,   0,   0, -65,  -9, -22,  45, -26,  36],
        [  0,   0,   0,   0,   0,  78,  45,  -1,  51, -14],
        [  0,   0,   0,   0,   0,   0,  85,  66,  42, -28],
        [  0,   0,   0,   0,   0,   0,   0, 124,  12, -29],
        [  0,   0,   0,   0,   0,   0,   0,   0,  31,  45],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,  34]]),
 array([ 45,  16,  50,  54, -23,  14,  21,  21,  10,   3]))

In [500]:
import plotly.graph_objs as go

def plot_matrix_evolution(evo, title):
    window_length = 1
    fig = go.Figure()
    for step in range(len(evo)):
        fig.add_trace(go.Heatmap(z=evo[step][::-1],colorscale="RdBu",zmid=0))
    fig.data[0].visible = True
    steps = []
    for i in range(len(fig.data)):
        step = dict(
            method="update",
            args=[{"visible": [False] * len(fig.data)},
                  {"title": title},
                  ],
            label=str(window_length * i))
        step["args"][0]["visible"][i] = True
        steps.append(step)

    sliders = [dict(
        active=0,
        pad={"t": 5},
        steps=steps
    )]

    fig.update_layout(sliders=sliders)

    fig.show()

In [501]:
plot_matrix_evolution(evo, "Gauss algorithm matrix evolution")

In [502]:
x_gauss = substitution_method(A_gauss, b_gauss, n=n)
x_gauss

[-0.2719105986809965,
 0.5127898662943627,
 -0.5837056418925273,
 0.013491830440477892,
 0.4214942322984342,
 0.043166947423659945,
 0.04711301304509071,
 0.1711682071371733,
 0.19449715370018975,
 0.08823529411764706]

Fie $x_{\text {Gauss }}$ soluţia aproximativă calculată. Să se verifice soluţia afişând următoarea normă:
$$
\left\|A^{i n i t} x_{G a u s s}-b^{i n i t}\right\|_{2}
$$
$A^{\text {init }}$ şi $b^{\text {init }}$ sunt datele iniţiale, nu cele modificate pe parcursul algoritmului. Am notat cu $\|\cdot\|_{2}$ norma Euclidiană. Această normă ar trebui să fie mai mică decât $10^{-6}$, dacă aţi implementat corect metoda eliminării Gauss.

In [503]:
from numpy.linalg import norm, solve, inv
def get_norm(a):
    print(a)
    norm_l2 = norm(a)
    return norm_l2

In [504]:
get_norm(A @ x_gauss - b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


1.475552811121985e-14

Folosindu-se una din bibliotecile menţionate în pagina laboratorului, să se calculeze şi să se afişeze soluţia sistemului $A x=b$ şi inversa matricei $A, x_{b i b l}$ şi $A_{b i b l}^{-1}$. Să se afişeze următoarele norme:
$$
\begin{gathered}
\left\|x_{\text {Gauss }}-x_{\text {bibl }}\right\|_{2} \\
\left\|x_{\text {Gauss }}-A_{\text {bibl }}^{-1} b^{i n i t}\right\|_{2} .
\end{gathered}
$$
Aceste norme ar trebui să fie mai mici decât $10^{-6}$.

In [505]:
def lib_solve(A,b):
    return solve(A,b)

In [506]:
x_lib = lib_solve(A, b)
x_lib

array([-0.2719106 ,  0.51278987, -0.58370564,  0.01349183,  0.42149423,
        0.04316695,  0.04711301,  0.17116821,  0.19449715,  0.08823529])

In [507]:
get_norm(x_gauss - x_lib)

[ 0.  0.  0.  0.  0.  0. -0.  0.  0.  0.]


9.959186318969168e-17

In [508]:
def lib_inv(A):
    return inv(A)

In [509]:
get_norm(x_gauss - lib_inv(A) @ b)

[ 0.  0.  0.  0. -0.  0. -0.  0.  0.  0.]


2.404767262039403e-16

### 3. Calculul inversei unei matrice folosind metoda lui Gauss

Dacă se cunoaşte o metodă numerică de rezolvare a sistemelor liniare (în cazul de faţă se va folosi algoritmul de eliminare Gauss), coloanele matricei inverse se pot aproxima rezolvând $n$ sisteme liniare.
Coloana $j$ a matricei $A^{-1}$ se aproximează rezolvând sistemul liniar:
$$
\begin{aligned}
&A x=e_{j}, j=1,2, \ldots, n, \\
&e_{j}=(0, \ldots, 1,0 \ldots, 0)^{T}, 1 \text { este pe poziţia } j \text { în vectorul } e_{j}
\end{aligned}
$$
Procedura de calcul a matricei $A_{\text {Gauss }}^{-1}$ este următoarea:
- Se calculează eliminarea Gauss a matricei extinse $\left[A, I_{n}\right] \in \mathbb{R}^{n \times 2 n}\left(I_{n}\right.$ este matricea unitate de dimensiune $n$ ). Se adaptează varianta a 2-a a algoritmului de eliminare Gauss cu pivotare parţială, astfel încât să modifice toate coloanele matricei $I_{n}$ simultan, împreună cu transformarea matricei $A$ în formă superior triunghiulară. În varianta a 2 -a a algoritmului descrisă mai sus se face transformarea Gauss a matricei $[A, b] \in \mathbb{R}^{n \times(n+1)}$.
La final, matricea va avea următoarea formă $\left[R, I_{\text {transformat }}\right]$ unde $R$ este forma superior triunghiulară a matricei $A$ iar $I_{\text {transformat }}$ este matricea $I_{n}$ modificată conform algoritmului de eliminare Gauss.
- for $j=1, \ldots, n$
  1. $b=$ coloana $j$ a matricei $I_{\text {transformat }}$;
  2. se rezolvă sistemul superior triunghiular $R x=b$, folosind metoda substituţiei inverse, se obţine soluţia $x^{*}\left(x^{*}\right.$ este soluţia sistemului liniar $A x=e_{j}$);
  3. se memorează $x^{*}$ în coloana $j$ a matricei $A_{\text {Gauss }}^{-1}$;

Procedura de mai sus detaliază, în fapt, rezolvarea numerică a ecuaţiei matriceale:

$$A X=I_{n}, X \in \mathbb{R}^{n \times n}, I_{n}=\text { matricea unitate. }$$

In [510]:
def get_column(matrix, i):
    return [row[i] for row in matrix]

In [511]:
def get_inv(A):
    n = len(A[0])
    I = np.eye(n)
    eps = 10 ** (-6)
    aug_A = np.c_[A, I]

    l = 0
    pivot = search_pivot(aug_A, l, n)
    if pivot != l:
        aug_A[[l, pivot]] = aug_A[[pivot, l]]
    while l < n - 1 and abs(aug_A[l][l] > eps):
        for i in range(l + 1, n):
            aug_A[i][l] = aug_A[i][l] / aug_A[l][l]
            for j in range(l + 1, 2 * n):
                aug_A[i][j] = aug_A[i][j] - aug_A[i][l] * aug_A[l][j]
        l = l + 1
        pivot = search_pivot(aug_A, l, n)
        if pivot != l:
            aug_A[[l, pivot]] = aug_A[[pivot, l]]

    R = np.zeros((n, n))
    I_t = np.zeros((n, n))
    for i in range(0, n):
        R[i] = aug_A[i][:n]
    for i in range(0, n):
        I_t[i] = aug_A[i][n:]

    inversa = np.zeros((n , n))
    for i in range(n):
        b = get_column(I_t, i)
        a_res, b_res,ev = gauss_algorithm(R, b, n)
        x = substitution_method(a_res, b_res, n)
        print("x= ",x)
        for j in range(n):
            inversa[j][i] = x[j]
    return inversa

In [512]:
my_inv = get_inv(A)
my_inv @ A

x=  [0.010309278350515464, 0.0, -0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
x=  [-0.008222876779577809, 0.011904761904761904, -0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
x=  [-0.0006847950595149157, 0.01570048309178744, -0.014492753623188406, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
x=  [-0.004500808595601904, -0.009446633570055731, 0.005765934237182485, 0.010752688172043012, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
x=  [0.0053732907443813874, 0.0008243042604893938, 0.0017477613550544832, 0.01240694789081886, -0.015384615384615385, 0.0, 0.0, 0.0, 0.0, 0.0]
x=  [0.007769442448511615, -0.011660758888974805, -0.0007553284713711945, -0.0017390935505079428, -0.0017751479289940828, 0.01282051282051282, 0.0, 0.0, 0.0, 0.0]
x=  [-0.007607901930894168, 0.009295850332354048, 0.0004397343225695797, -0.006494279330361654, -0.0030421162547859377, -0.006787330316742082, 0.011764705882352941, 0.0, 0.0, 0.0]
x=  [-0.0005008930596395916, 0.0003664186267282034, -0.00494877066745139, -0.006696403580776476, 0.00718800175156

array([[ 1.,  0.,  0.,  0.,  0.,  0., -0., -0.,  0., -0.],
       [ 0.,  1., -0., -0., -0.,  0., -0.,  0., -0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0., -0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0., -0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  1., -0., -0.,  0., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

Folosind algoritmul de eliminare Gauss, calculaţi o aproximare a inversei acestei matrice, $A_{\text {Gauss }}^{-1}$. Să se afişeze:
$$
\left\|A_{\text {Gauss }}^{-1}-A_{\text {bibl }}^{-1}\right\|
$$
Folosiţi orice normă matriceală este implementată în bibliotecă.

In [513]:
get_norm(lib_inv(A) - my_inv)

[[ 0.  0. -0.  0.  0. -0.  0. -0. -0.  0.]
 [ 0.  0.  0.  0. -0.  0.  0. -0. -0.  0.]
 [ 0.  0.  0.  0.  0. -0. -0.  0.  0. -0.]
 [ 0.  0.  0.  0.  0. -0. -0. -0.  0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


1.961853645157958e-17

### Bonus (25pt)
: Să se adapteze algoritmul de eliminare Gauss cu pivotare parţială pentru matrice tridiagonale de forma:
$$
A=\left(\begin{array}{cccccccc}
a_{1} & b_{1} & 0 & 0 & \cdots & 0 & 0 & 0 \\
c_{1} & a_{2} & b_{2} & 0 & \cdots & 0 & 0 & 0 \\
0 & c_{2} & a_{3} & b_{3} & \cdots & 0 & 0 & 0 \\
\vdots & & & & & & & \\
0 & 0 & 0 & 0 & \cdots & c_{n-2} & a_{n-1} & b_{n-1} \\
0 & 0 & 0 & 0 & \cdots & 0 & c_{n-1} & a_{n}
\end{array}\right)
$$
Să se calculeze soluţia sistemului $A x=g$. La sfârşitul rulării algoritmului de eliminare Gauss pentru matrice tridiagonală, se ajunge la o matrice de forma:
$$
R=\left(\begin{array}{cccccccc}
d_{1} & e_{1} & f_{1} & 0 & \cdots & 0 & 0 & 0 \\
0 & d_{2} & e_{2} & f_{2} & \cdots & 0 & 0 & 0 \\
\vdots & & & & & & & \\
0 & 0 & 0 & 0 & \cdots & d_{n-2} & e_{n-2} & f_{n-2} \\
0 & 0 & 0 & 0 & \cdots & 0 & d_{n-1} & e_{n-1} \\
0 & 0 & 0 & 0 & \cdots & 0 & 0 & d_{n}
\end{array}\right)
$$
La aplicarea algoritmului de eliminare Gauss, să se lucreze doar cu cei 6 vectori $a, b, c, d, e, f$.

In [514]:
# To be completed by the brave ones