# Tema 3

**Topics:**
* stocarea matricelor *rare*
* operatii elementare cu matrici *rare*

In [1]:
import numpy as np
import random

# to be implemented
from tema3 import RareMatrix

random.seed(1)
np.random.seed(1)

In [2]:
# Let's generate a random rare matrix
n = 5

def generate_random_rare_matrix(n, approx_density=0.1):
    m = np.zeros((n, n))
    for i in range(int(n*n*approx_density)):
        line = random.randint(0, n - 1)
        column = random.randint(0, n - 1)
        value = random.randint(0, 100) # let's hardcode the max value 
        
        m[line, column] = value
    
    return m

generate_random_rare_matrix(n, approx_density=0.1)

array([[ 0.,  0., 15.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 97.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [3]:
# Let's use a pre-defined function for the same task
import scipy.sparse as sparse

sparse.random(n, n, random_state=0, density=0.25).A

array([[0.        , 0.33739616, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.14035078, 0.95715516, 0.        ],
       [0.64817187, 0.        , 0.        , 0.        , 0.87008726],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.36824154, 0.        ]])

In [4]:
# Let's generate a random symmetric rare matrix
n = 10

def generate_symmetric_random_rare_matrix(n, approx_density=0.1):
    m = np.zeros((n, n))
    for i in range(int(n*n*approx_density / 2)):
        line = random.randint(0, n - 1)
        column = random.randint(0, n - 1)
        value = random.randint(0, 100) # let's hardcode the max value 
        
        m[line, column] = value
        m[column, line] = value 
        
    return m

generate_symmetric_random_rare_matrix(n, approx_density=0.2)

array([[ 0.,  0.,  0.,  0.,  0.,  2.,  0., 34., 28.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., 54.,  0.,  0., 13.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 54.,  0.,  0.,  0.,  0.,  0., 97.],
       [34.,  0.,  0.,  0.,  0.,  0.,  0., 60.,  0.,  0.],
       [28.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 13.,  0.,  0., 97.,  0.,  0.,  0.]])

Alte tipuri de matrice rare: https://en.wikipedia.org/wiki/Sparse_matrix

### Memorarea matricelor rare şi simetrice (schema de memorare economică)
Un vector 'rar' este un vector cu 'puține' elemente nenule. Un asemenea vector se memorează eficient într-o structură care va reține doar valorile nenule și poziția în vector a respectivei valori:
$$
\left\{(v a l \neq 0, i) ; x_{i}=v a l\right\} .
$$
$\mathrm{O}$ matrice rară poate fi memorată economic ca un vector de vectori memorați rar - fiecare linie a matricei se memorează într-un vector rar.
În cazul matricelor simetrice se vor memora pentru fiecare linie elementele nenule din partea inferior triunghiulară a matricei.
Pentru linia $\boldsymbol{i}$, se vor memora elementele nenule din partea inferior triunghiulară a matricei $\boldsymbol{A}$ :
$$
\left\{(v a l \neq 0, j) ; a_{i j}=v a l, j \leq i\right\}
$$

#### Exemplu:

Matricea:
$$
A=\left(\begin{array}{ccccc}
102.5 & 0.0 & 2.5 & 0.0 & 0.73 \\
0.0 & 104.88 & 1.05 & 0.0 & 0.33 \\
2.5 & 1.05 & 100.0 & 0.0 & 0.0 \\
0.0 & 0.0 & 0.0 & 101.3 & 1.5 \\
0.73 & 0.33 & 0.0 & 1.5 & 102.23
\end{array}\right)
$$
se poate memora economic astfel:
$$
\begin{aligned}
&\{\{(102.5,0)\}, / / \text { linia } 0 \\
&\{(104.88,1)\}, / / \text { linia } 1 \\
&\{(2.5,0),(1.05,1),(100.0,2)\}, / / \text { linia } 2 \\
&\{(101.3,3)\}, / / \text { linia } 3 \\
&\{(1.5,3),(0.73,0),(102.23,4),(0.33,1)\}\} . / / \text { linia } 4
\end{aligned}
$$

### Ok, acum enuntul temei
În fișierele **a.txt**, **b.txt**, **a plus b.txt**, **a ori_a.txt** postate pe pagina laboratorului, sunt memorate, pentru 4 matrice rare (cu 'putine' elemente $a_{i j}$ $\neq 0)$ şi simetrice, următoarele elemente:
- $\boldsymbol{n}$ dimensiunea datelor,
- $a_{i j} \neq 0, i, j$ cu $j \leq i$ - elementele nenule din partea inferior triunghiulară a matricei rare şi simetrice $A \in \mathbb{R}^{n \times n}$, indicii de linie și indicii de coloană ai respectivelor elemente.

Folosind fișierele atașate, să se citească dimensiunea matricelor și să se genereze structurile de date necesare pentru memorarea economică a matricei rare și simetrice(schema economică de memorare este descrisă mai jos). Se presupune că elementele nenule ale matricei sunt plasate aleator în fișier (nu sunt ordonate după indicii de linie sau de coloană, sau altfel). Verificați că elementele din fișierele postate respectă regula $\boldsymbol{j} \leq \boldsymbol{i}$.

Fie $\boldsymbol{A}, \boldsymbol{B} \in \mathbb{R}^{n \times n}$ două matrice rare şi simetrice cu elemente reale. Folosind schema de memorare rară prezentată mai jos, să se calculeze:
- $\boldsymbol{A}+\boldsymbol{B}$ suma matricelor,
- $A^{2}=A^{*} A$ produsul matricei $A$ cu ea însăși.
Să se verifice că suma/produsul matricelor din fișierele a.txt și b.txt este matricea din fișierul a plus_b.txt/a_ori_a.txt. Două elemente care au aceiași indici de linie și coloană $(\boldsymbol{i}, \boldsymbol{j})$ sunt considerate egale dacă $\left|\boldsymbol{c}_{i j}-\boldsymbol{d}_{i j}\right|<\varepsilon$. Considerați $\varepsilon$ dată de intrare în program (de exemplu, $\varepsilon=10^{-6}$ ).

#### Observatii

1. La rezolvarea problemelor de mai sus să nu se recurgă la alocarea de matrice clasice și nici să nu se folosească o funcție val(i,j) care returnează pentru orice $(\boldsymbol{i}, \boldsymbol{j})$ valoarea elementului corespunzător din matrice. 

2. În cazul înmulțirii matricelor, gradul de umplere al matricei (numărul de elemente nenule din matrice) nu poate fi precizat dinainte. Este posibil ca matricea rezultat să fie ,plină”. Chiar dacă matricea este ,plină”, folosiţi schema de memorare rară pentru memorarea matricei produs.

3. Implementarea schemei de memorare rară descrisă în acest fișier este obligatorie (neimplementarea ei se penalizează). Cei care aleg o altă schemă de memorare a matricelor rare trebuie să prezinte suplimentar un fișier documentație care să explice schema folosită și să prezinte un exemplu (cel mult $5 \times 5$, se poate folosi exemplul din temă) care să precizeze conținutul structurilor de date utilizate pentru memorarea matricei rare.

4. Dacă în fișierele atașate apar mai multe valori cu aceiași indici de linie și coloană:
$$
\begin{aligned}
&v a l_{1}, i, j \\
&\ldots \\
&v a l_{2}, i, j \\
&\ldots \\
&v a l_{k}, i, j
\end{aligned}
$$
o astfel de situație are următoarea semnificație:
$$
a_{i j}=v a l_{1}+v a l_{2}+\cdots+v a l_{k} .
$$

In [5]:
# Let's read the files

urls = {
    "a": "https://profs.info.uaic.ro/~ancai/CN/lab/3/a.txt",
    "b": "https://profs.info.uaic.ro/~ancai/CN/lab/3/b.txt",
    "a_plus_b": "https://profs.info.uaic.ro/~ancai/CN/lab/3/a_plus_b.txt",
    "a_ori_a": "https://profs.info.uaic.ro/~ancai/CN/lab/3/a_ori_a.txt"
}

a = RareMatrix.from_url(urls["a"])
b = RareMatrix.from_url(urls["b"])
a_plus_b = RareMatrix.from_url(urls["a_plus_b"])
a_ori_a = RareMatrix.from_url(urls["a_ori_a"])

Exemplu de stocare a valorilor rare.

In [6]:
# print sparse representation of lines 0, 100, 1000
a.rare_values[0], a.rare_values[100], a.rare_values[1000]

({0: 506.5},
 {18: 8.0,
  28: 19.0,
  36: 13.5,
  100: 481.5,
  17: 5.0,
  41: 19.0,
  57: 15.0,
  71: 21.0,
  77: 21.5,
  79: 20.0,
  89: 14.5},
 {684: 18.5, 1000: 213.5, 155: 2.0, 365: 21.5, 873: 16.5})

In [7]:
# print sparse representation of lines 0, 100, 1000
b.rare_values[0], b.rare_values[100], b.rare_values[1000]

({0: 524.0},
 {10: 30.0,
  14: 4.0,
  22: 10.0,
  40: 24.5,
  100: 430.5,
  9: 15.5,
  77: 15.0,
  79: 25.5},
 {378: 4.0, 388: 17.5, 1000: 185.5})

#### Adunarea matricelor rare

In [8]:
# you'll need to override the "+" operator
my_a_plus_b = a + b

In [9]:
my_a_plus_b.rare_values[100], a_plus_b.rare_values[100]

({18: 8.0,
  28: 19.0,
  36: 13.5,
  100: 912.0,
  17: 5.0,
  41: 19.0,
  57: 15.0,
  71: 21.0,
  77: 36.5,
  79: 45.5,
  89: 14.5,
  10: 30.0,
  14: 4.0,
  22: 10.0,
  40: 24.5,
  9: 15.5},
 {10: 30.0,
  14: 4.0,
  18: 8.0,
  22: 10.0,
  28: 19.0,
  36: 13.5,
  40: 24.5,
  100: 912.0,
  9: 15.5,
  17: 5.0,
  41: 19.0,
  57: 15.0,
  71: 21.0,
  77: 36.5,
  79: 45.5,
  89: 14.5})

In [10]:
# you'll need to override the "==" operator
my_a_plus_b == a_plus_b

True

#### Ridicarea la putere a matricelor (sau inmultirea matricelor)

In [11]:
%%time
# you'll need to override the "**" operator
my_a_ori_a = a ** 2

CPU times: user 5min, sys: 806 ms, total: 5min
Wall time: 5min 1s


In [14]:
my_a_ori_a.rare_values[5], a_ori_a.rare_values[5]

({0: 399.75, 1: 1484.5, 2: 20184.5, 3: 1704.75, 4: 182.0, 5: 472852.75},
 {0: 399.75, 2: 20184.5, 4: 182.0, 1: 1484.5, 3: 1704.75, 5: 472852.75})

In [13]:
my_a_ori_a == a_ori_a

True